import  { NavbarDemo } from "./components/ui/Navbar"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <NavbarDemo />
        {children}
        
        </body>
    </html>
  )
}
